version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "_"
    labels:
      - "dependabot"
    reviewers:
      - "@hilltop"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "_"
    labels:
      - "dependabot"
    reviewers:
      - "@hilltop"
    commit-message:
      prefix: "ci"
      include: "scope"