name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Delete merged branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          REPO_NAME="${{ github.repository }}"
          # Skip deletion if branch is main, master, or develop
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "develop" ]]; then
            echo "Skipping deletion of protected branch: $BRANCH_NAME"
            exit 0
          fi
          echo "Deleting merged branch: $BRANCH_NAME"
          gh api \
            --method DELETE \
            /repos/$REPO_NAME/git/refs/heads/$BRANCH_NAME \
            || echo "Branch $BRANCH_NAME may have already been deleted or doesn't exist remotely"
